### ISSUE TITLE
Caused by java.lang.NullPointerException Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference

### ISSUE THREAD

**Issue by changjiashuai** [Lowae/Shadows#1]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
       at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:139)
       at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:117)
       at com.lowae.shadows.ShadowAbilityImpl.initAttrs(ShadowAbilityImpl.kt:71)
       at com.lowae.shadows.widgets.ShadowFrameLayout.<init>(ShadowFrameLayout.kt:21)
       at com.lowae.shadows.widgets.ShadowFrameLayout.<init>(ShadowFrameLayout.kt:11)
       at com.lowae.shadows.widgets.ShadowFrameLayout.<init>(ShadowFrameLayout.kt:20)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
       at com.airbnb.epoxy.EpoxyModel.buildView(EpoxyModel.java:97)
       at com.airbnb.epoxy.BaseEpoxyAdapter.onCreateViewHolder(BaseEpoxyAdapter.java:100)
       at com.airbnb.epoxy.BaseEpoxyAdapter.onCreateViewHolder(BaseEpoxyAdapter.java:20)
       at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
       at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2028)
       at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
       at android.view.Choreographer.doCallbacks(Choreographer.java:688)
       at android.view.Choreographer.doFrame(Choreographer.java:620)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6388)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

**Comment by Lowae** [comment]
https://github.com/Lowae/Shadows/pull/2
